<?php

return [
    [
        'id' => 1,
        'title' => 'Técnicas de Intervención en Psicoterapia Breve',
        'instructor' => 'Dra. María González',
        'startDate' => '2026-03-20',
        'originalPrice' => 120000,
        'discountPrice' => 89000,
        'modalidad' => 'En Vivo',
        'categoria' => 'Psicología Clínica y Salud Mental en la Adultez',
        'image' => 'https://images.unsplash.com/photo-1590649880765-91b1956b8276?w=400&h=250&fit=crop',
        'status' => 'En progreso',
    ],
    [
        'id' => 2,
        'title' => 'Salud Mental en Contexto Escolar',
        'instructor' => 'Ps. Carlos Ruiz',
        'startDate' => '2026-03-20',
        'originalPrice' => 95000,
        'discountPrice' => 75000,
        'modalidad' => 'En Vivo',
        'categoria' => 'Psicología Clínica y Salud Mental Infantil y Adolescente',
        'image' => 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&h=250&fit=crop',
        'status' => 'En progreso',
    ],
    [
        'id' => 3,
        'title' => 'Protocolos de desregulación y acompañamiento emocional en contextos educativos',
        'instructor' => 'Dr. Andrés Morales',
        'startDate' => '2026-03-25',
        'originalPrice' => 110000,
        'discountPrice' => 85000,
        'modalidad' => 'En Vivo',
        'categoria' => 'Educación y Neurodesarrollo',
        'image' => 'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=400&h=250&fit=crop',
        'status' => 'En progreso',
    ],
    [
        'id' => 4,
        'title' => 'Evaluación Pericial Psicológica en Contextos Forenses',
        'instructor' => 'Ps. Laura Soto',
        'startDate' => '2026-04-10',
        'originalPrice' => 100000,
        'discountPrice' => 79000,
        'modalidad' => 'Online',
        'categoria' => 'Psicología Jurídica y Forense',
        'image' => 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400&h=250&fit=crop',
        'status' => 'Próximamente',
    ],
    [
        'id' => 5,
        'title' => 'Neurociencia Aplicada a la Psicoterapia',
        'instructor' => 'Dr. Felipe Vargas',
        'startDate' => '2026-04-15',
        'originalPrice' => 130000,
        'discountPrice' => 99000,
        'modalidad' => 'En Vivo',
        'categoria' => 'Neurociencias',
        'image' => 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=250&fit=crop',
        'status' => 'Próximamente',
    ],
    [
        'id' => 6,
        'title' => 'Liderazgo y Bienestar Organizacional',
        'instructor' => 'Dra. Valentina Pérez',
        'startDate' => '2026-04-20',
        'originalPrice' => 115000,
        'discountPrice' => 90000,
        'modalidad' => 'Online',
        'categoria' => 'Psicología Organizacional y del Trabajo',
        'image' => 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=400&h=250&fit=crop',
        'status' => 'Próximamente',
    ],
    [
        'id' => 7,
        'title' => 'Evaluación Psicológica Infantil con WISC-V',
        'instructor' => 'Ps. Rodrigo Díaz',
        'startDate' => '2026-05-01',
        'originalPrice' => 105000,
        'discountPrice' => 82000,
        'modalidad' => 'Online',
        'categoria' => 'Psicología Clínica y Salud Mental Infantil y Adolescente',
        'image' => 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=400&h=250&fit=crop',
        'status' => 'Nuevo',
    ],
    [
        'id' => 8,
        'title' => 'Intervención en Crisis y Primeros Auxilios Psicológicos',
        'instructor' => 'Dra. Camila Torres',
        'startDate' => '2026-05-10',
        'originalPrice' => 98000,
        'discountPrice' => 72000,
        'modalidad' => 'Presencial',
        'categoria' => 'Psicología Clínica y Salud Mental en la Adultez',
        'image' => 'https://images.unsplash.com/photo-1527137342181-19aab11a8ee8?w=400&h=250&fit=crop',
        'status' => 'Nuevo',
    ],
];