<?php

return [
    [
        'id' => 1,
        'title' => 'Técnicas de Intervención en Psicoterapia Breve',
        'instructor' => 'Dra. María González',
        'startDate' => '2026-03-20',
        'originalPrice' => 120000,
        'discountPrice' => 89000,
        'modalidad' => 'En Vivo',
        'categoria' => 'Psicología Clínica y Salud Mental en la Adultez',
        'tipo' => 'Curso',
        'image' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=250&fit=crop',
        'status' => 'En progreso',
        'tags' => ['Trauma', 'Psicoterapia'],
        'horas' => 24,
        'rating' => 4.8,
        'popularity' => 95,
    ],
    [
        'id' => 2,
        'title' => 'Evaluación con Escala de Observación ADOS-2',
        'instructor' => 'Ps. Carlos Ruiz',
        'startDate' => '2026-03-20',
        'originalPrice' => 95000,
        'discountPrice' => 75000,
        'modalidad' => 'En Vivo',
        'categoria' => 'Psicología Clínica y Salud Mental Infantil y Adolescente',
        'tipo' => 'Acreditación',
        'image' => 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400&h=250&fit=crop',
        'status' => 'En progreso',
        'tags' => ['Ados', 'Autismo'],
        'horas' => 16,
        'rating' => 5.0,
        'popularity' => 88,
    ],
    [
        'id' => 3,
        'title' => 'Intervención Temprana en Autismo y Neurodesarrollo',
        'instructor' => 'Dr. Andrés Morales',
        'startDate' => '2026-03-25',
        'originalPrice' => 110000,
        'discountPrice' => 85000,
        'modalidad' => 'En Vivo',
        'categoria' => 'Educación y Neurodesarrollo',
        'tipo' => 'Especialización',
        'image' => 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=250&fit=crop',
        'status' => 'En progreso',
        'tags' => ['Autismo', 'Peers'],
        'horas' => 48,
        'rating' => 4.9,
        'popularity' => 76,
    ],
    [
        'id' => 4,
        'title' => 'Evaluación Pericial Psicológica en Contextos Forenses',
        'instructor' => 'Ps. Laura Soto',
        'startDate' => '2026-04-10',
        'originalPrice' => 100000,
        'discountPrice' => 79000,
        'modalidad' => 'Online',
        'categoria' => 'Psicología Jurídica y Forense',
        'tipo' => 'Diplomados',
        'image' => 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&h=250&fit=crop',
        'status' => 'Próximamente',
        'tags' => ['Trauma'],
        'horas' => 120,
        'rating' => 4.7,
        'popularity' => 65,
    ],
    [
        'id' => 5,
        'title' => 'Neurociencia Aplicada a la Psicoterapia',
        'instructor' => 'Dr. Felipe Vargas',
        'startDate' => '2026-04-15',
        'originalPrice' => 130000,
        'discountPrice' => 99000,
        'modalidad' => 'En Vivo',
        'categoria' => 'Neurociencias',
        'tipo' => 'Curso',
        'image' => 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=250&fit=crop',
        'status' => 'Próximamente',
        'tags' => ['ADI-R', 'Autismo'],
        'horas' => 32,
        'rating' => 5.0,
        'popularity' => 99,
    ],
    [
        'id' => 6,
        'title' => 'Liderazgo y Bienestar Organizacional',
        'instructor' => 'Dra. Valentina Pérez',
        'startDate' => '2026-04-20',
        'originalPrice' => 115000,
        'discountPrice' => 90000,
        'modalidad' => 'Online',
        'categoria' => 'Psicología Organizacional y del Trabajo',
        'tipo' => 'Especialización',
        'image' => 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=400&h=250&fit=crop',
        'status' => 'Próximamente',
        'tags' => ['Peers'],
        'horas' => 60,
        'rating' => 4.6,
        'popularity' => 55,
    ],
    [
        'id' => 7,
        'title' => 'Evaluación Psicológica Infantil con WISC-V',
        'instructor' => 'Ps. Rodrigo Díaz',
        'startDate' => '2026-05-01',
        'originalPrice' => 105000,
        'discountPrice' => 82000,
        'modalidad' => 'Online',
        'categoria' => 'Psicología Clínica y Salud Mental Infantil y Adolescente',
        'tipo' => 'Acreditación',
        'image' => 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&h=250&fit=crop',
        'status' => 'Nuevo',
        'tags' => ['Wisc', 'WAIS'],
        'horas' => 20,
        'rating' => 4.9,
        'popularity' => 82,
    ],
    [
        'id' => 8,
        'title' => 'Intervención en Crisis y Primeros Auxilios Psicológicos',
        'instructor' => 'Dra. Camila Torres',
        'startDate' => '2026-05-10',
        'originalPrice' => 98000,
        'discountPrice' => 72000,
        'modalidad' => 'Presencial',
        'categoria' => 'Psicología Clínica y Salud Mental en la Adultez',
        'tipo' => 'Curso',
        'image' => 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=400&h=250&fit=crop',
        'status' => 'Nuevo',
        'tags' => ['Trauma', 'ADI-R'],
        'horas' => 28,
        'rating' => 4.8,
        'popularity' => 71,
    ],
];